version: '3.4'

services:
  postgre:
    image: postgres:15.1
    ports:
      - '5432:5432'
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgre:
    driver_opts:
      type: tmpfs
      device: tmpfs
